# typed: false
# frozen_string_literal: true

# This file was generated from the md-fixup repository.
# Do not edit this file directly. Instead, update the version and SHA256
# in this file when releasing a new version.

class MdFixup < Formula
  desc "Markdown linter that normalizes formatting and wraps text"
  homepage "https://github.com/yourusername/md-fixup"
  url "https://github.com/yourusername/md-fixup/archive/v0.1.0.tar.gz"
  sha256 "calculated-sha256-here"
  license "MIT"
  head "https://github.com/yourusername/md-fixup.git", branch: "main"

  depends_on "rust" => :build

  def install
    cd "rust" do
      system "cargo", "install", "--path", ".", "--root", prefix, "--locked"
    end
  end

  test do
    (testpath/"test.md").write "# Test\n\nSome text."
    system "#{bin}/md-fixup", "test.md"
    assert_match "# Test", File.read("test.md")
  end
end
